#http://wiki.osdev.org/Makefile

# Common files, folders and configuration.
BLDDIR := build
BINDIR := $(BLDDIR)/bin
LIBDIR := $(BLDDIR)/lib
EXEFILE := $(BINDIR)/%
EXEDEPFILE := $(BINDIR)/%.d
AR := ar
CC := g++
ETAGS := etags
MKDIR := mkdir
RM := rm
BASE_CFLAGS = -Wall -O2

# Bond library files, folders and configuration.
INCLUDEDIR := include
SRCDIR := source
SRCFILE := $(SRCDIR)/%.cpp
OBJDIR := $(BLDDIR)/obj/bond
OBJFILE := $(OBJDIR)/%.o
OBJDEPFILE := $(OBJDIR)/%.d
SRCFILES := $(wildcard $(SRCDIR)/*.cpp)
OBJFILES := $(patsubst $(SRCFILE),$(OBJFILE),$(SRCFILES))
DEPFILES := $(patsubst $(SRCFILE),$(OBJDEPFILE),$(SRCFILES))
LIB := $(LIBDIR)/bond.a
CFLAGS := $(BASE_CFLAGS) -I$(INCLUDEDIR) -Isource

# Test Framework library files, folders and configuration.
TFSRCDIR := test/framework
TFSRCFILE := $(TFSRCDIR)/%.cpp
TFOBJDIR := $(BLDDIR)/obj/framework
TFOBJFILE := $(TFOBJDIR)/%.o
TFOBJDEPFILE := $(TFOBJDIR)/%.d
TFSRCFILES := $(wildcard $(TFSRCDIR)/*.cpp)
TFOBJFILES := $(patsubst $(TFSRCFILE),$(TFOBJFILE),$(TFSRCFILES))
TFDEPFILES := $(patsubst $(TFSRCFILE),$(TFOBJDEPFILE),$(TFSRCFILES))
TFLIB := $(LIBDIR)/framework.a
TFCFLAGS := $(BASE_CFLAGS) -I$(INCLUDEDIR) -Itest

# Unit Test files, folders and configuration.
UTSRCDIR := test
UTSRCFILE := $(UTSRCDIR)/%.cpp
UTEST := %
UTSRCFILES := $(wildcard $(UTSRCDIR)/*.cpp)
UTEXES := $(patsubst $(UTSRCFILE),$(EXEFILE),$(UTSRCFILES))
UTDEPFILES := $(patsubst $(UTSRCFILE),$(EXEDEPFILE),$(UTSRCFILES))
UTESTS := $(patsubst $(UTSRCFILE),$(UTEST),$(UTSRCFILES))
UTCFLAGS := $(BASE_CFLAGS) -I$(INCLUDEDIR) -Itest

.PHONY: all clean deepclean test tags

# Not sure why unit test executables are considered to be generated by implicit rules when the rule
# is listed below, but they are. The consequence is that make deletes the executables after running
# them unless they are marked as precious.
.PRECIOUS: $(EXEFILE)

all: $(LIB)

clean:
	$(RM) -rf $(BLDDIR)

deepclean:
	$(RM) -rf $(BLDDIR) TAGS vs/*/*.sdf vs/*/*.suo vs/*/*.user vs/*/ipch

tags :
	rm -f TAGS
	$(ETAGS) --language-force=C++ -R $(PWD)/$(INCLUDEDIR) $(PWD)/$(SRCDIR) $(PWD)/$(UTSRCDIR)

# Bond library targets.
$(LIB): $(OBJFILES)
	@$(MKDIR) -p $(LIBDIR)
	$(AR) rcs $(LIB) $?

-include $(DEPFILES)

$(OBJFILE): $(SRCFILE) Makefile
	@$(MKDIR) -p $(OBJDIR)
	$(CC) $(CFLAGS) -MMD -MP -c $< -o $@

# Test Framework targets.
framework: $(TFLIB)

$(TFLIB): $(TFOBJFILES)
	@$(MKDIR) -p $(LIBDIR)
	$(AR) rcs $(TFLIB) $?

-include $(TFDEPFILES)

$(TFOBJFILE): $(TFSRCFILE) Makefile
	@$(MKDIR) -p $(TFOBJDIR)
	$(CC) $(TFCFLAGS) -MMD -MP -c $< -o $@

# Unit Test targets.
test: $(UTESTS)

$(UTEST): $(EXEFILE)
	$<

-include $(UTDEPFILES)

$(EXEFILE): $(UTSRCFILE) Makefile $(LIB) $(TFLIB)
	@$(MKDIR) -p $(BINDIR)
	$(CC) $(UTCFLAGS) -MMD -MP $< $(TFLIB) $(LIB) -o $@
